import { Router } from "express";
import { verifyJWT, isAdmin } from "../../middlewares/auth.middleware";
import { AdminController } from "./admin.controller";

const router = Router();

router.use(verifyJWT, isAdmin);

router.get("/management-catalog", AdminController.managementCatalog);
router.get("/dashboard", AdminController.dashboard);
router.get("/cms-pages", AdminController.cmsPages);
router.post("/cms-pages", AdminController.createCMSPage);
router.patch("/cms-pages/:id", AdminController.updateCMSPage);
router.delete("/cms-pages/:id", AdminController.deleteCMSPage);
router.get("/faqs", AdminController.faqs);
router.post("/faqs", AdminController.createFAQ);
router.patch("/faqs/:id", AdminController.updateFAQ);
router.delete("/faqs/:id", AdminController.deleteFAQ);
router.get("/blog-posts", AdminController.blogPosts);
router.post("/blog-posts", AdminController.createBlogPost);
router.patch("/blog-posts/:id", AdminController.updateBlogPost);
router.delete("/blog-posts/:id", AdminController.deleteBlogPost);
router.get("/announcements", AdminController.announcements);
router.post("/announcements", AdminController.createAnnouncement);
router.patch("/announcements/:id", AdminController.updateAnnouncement);
router.delete("/announcements/:id", AdminController.deleteAnnouncement);
router.get("/flash-sales", AdminController.flashSales);
router.post("/flash-sales", AdminController.createFlashSale);
router.patch("/flash-sales/:id", AdminController.updateFlashSale);
router.delete("/flash-sales/:id", AdminController.deleteFlashSale);
router.patch("/products/:id/feature", AdminController.featureProduct);
router.get("/warehouses", AdminController.warehouses);
router.post("/warehouses", AdminController.createWarehouse);
router.patch("/warehouses/:id", AdminController.updateWarehouse);
router.delete("/warehouses/:id", AdminController.deleteWarehouse);
router.get("/shipping-providers", AdminController.shippingProviders);
router.post("/shipping-providers", AdminController.createShippingProvider);
router.patch("/shipping-providers/:id", AdminController.updateShippingProvider);
router.delete("/shipping-providers/:id", AdminController.deleteShippingProvider);
router.get("/inventory", AdminController.inventory);
router.patch("/inventory/stock", AdminController.updateInventory);
router.get("/reports", AdminController.reports);
router.get("/activity-logs", AdminController.activityLogs);
router.get("/audit-logs", AdminController.auditLogs);
router.get("/system-config", AdminController.systemConfig);
router.patch("/system-config", AdminController.updateSystemConfig);
router.get("/backups", AdminController.backups);
router.post("/backups", AdminController.createBackup);
router.post("/backups/:id/restore-dry-run", AdminController.dryRunRestore);
router.post("/backups/:id/restore", AdminController.restoreBackup);
router.get("/people", AdminController.people);
router.patch("/users/:id/block", AdminController.blockUser);
router.patch("/partners/:id/status", AdminController.updatePartnerStatus);
router.post("/invites", AdminController.invite);
router.get("/payouts", AdminController.payouts);
router.post("/payouts", AdminController.createPayout);
router.patch("/payouts/:id/status", AdminController.updatePayoutStatus);
router.get("/payout-methods", AdminController.payoutMethods);
router.patch("/sellers/:sellerId/payout-methods/:methodId/status", AdminController.reviewPayoutMethod);
router.get("/seller-submissions", AdminController.sellerSubmissions);
router.patch("/seller-submissions/:type/:id/review", AdminController.reviewSellerSubmission);
router.get("/malls", AdminController.malls);
router.get("/mall-requests", AdminController.mallRequests);
router.get("/mall-creation-requests", AdminController.mallCreationRequests);
router.post("/malls", AdminController.createMall);
router.patch("/malls/:id", AdminController.updateMall);
router.patch("/malls/:id/review", AdminController.reviewMallCreation);
router.delete("/malls/:id", AdminController.deleteMall);
router.patch("/sellers/:id/mall", AdminController.assignSellerMall);
router.patch("/sellers/:id/mall-request", AdminController.reviewMallRequest);

export default router;
