import { StyleSheet, Platform } from "react-native";
import { Theme } from "@/src/theme/Provider/ThemeProvider";

export const createCartStyles = (theme: Theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background,
    ...(Platform.OS === "web" && {
      alignItems: "center",
    }),
  },
  mainWrapper: {
    flex: 1,
    width: "100%",
    maxWidth: 800,
  },
  scrollContent: {
    paddingBottom: Platform.OS === "web" ? 220 : 150, // More space on web for floating footer
  },
  walletLottie: {
    width: 60,
    height: 60,
  },
  header: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: theme.text,
  },
  itemCount: {
    fontSize: 14,
    color: theme.secondaryText,
    marginTop: 2,
  },
  // Item Card Styles
  card: {
    flexDirection: "row",
    padding: 12,
    marginHorizontal: 16,
    marginVertical: 6,
    borderRadius: 18,
    backgroundColor: theme.tertiaryBackground,
    borderWidth: 1,
    borderColor: theme.border,
    overflow: "hidden",
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 6,
      },
      android: {
        elevation: 1,
      },
    }),
  },
  deleteButton: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
    backgroundColor: theme.background,
    flexShrink: 0,
  },
  image: {
    width: 84,
    height: 108,
    borderRadius: 12,
    backgroundColor: theme.background,
    flexShrink: 0,
  },
  itemDetails: {
    flex: 1,
    marginLeft: 12,
    justifyContent: "space-between",
    minWidth: 0,
  },
  itemTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
    minWidth: 0,
  },
  itemName: {
    fontSize: 15,
    fontWeight: "700",
    color: theme.text,
    lineHeight: 20,
    flex: 1,
    minWidth: 0,
  },
  itemVariant: {
    fontSize: 12,
    color: theme.secondaryText,
    marginTop: 6,
    fontWeight: "500",
  },
  priceRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    marginTop: 10,
    gap: 8,
    minWidth: 0,
  },
  priceContainer: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
  },
  price: {
    fontSize: 16,
    fontWeight: "800",
    color: theme.text,
  },
  originalPriceStrikethrough: {
    fontSize: 12,
    color: theme.secondaryText,
    textDecorationLine: "line-through",
    marginTop: 2,
  },
  itemSubtotal: {
    fontSize: 11,
    color: theme.secondaryText,
    marginTop: 2,
    fontWeight: "600",
  },
  itemSubtotalRow: {
    flexDirection: "row",
    alignItems: "baseline",
    marginTop: 2,
  },
  itemSubtotalLabel: {
    fontSize: 11,
    color: theme.secondaryText,
    fontWeight: "600",
  },
  quantityContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.background,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: theme.border,
    paddingHorizontal: 3,
    paddingVertical: 3,
    flexShrink: 0,
  },
  qtyButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: theme.tertiaryBackground,
    justifyContent: "center",
    alignItems: "center",
  },
  qtyButtonDisabled: {
    opacity: 0.35,
  },
  qtyText: {
    fontSize: 14,
    fontWeight: "800",
    minWidth: 26,
    textAlign: "center",
    color: theme.text,
  },
  // Summary Styles
  summaryContainer: {
    marginTop: 16,
    marginHorizontal: 16,
    padding: 16,
    borderRadius: 16,
    backgroundColor: theme.tertiaryBackground,
    borderWidth: 1,
    borderColor: theme.border,
  },
  summaryHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  summaryHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
  },
  summaryHeaderTotal: {
    fontSize: 16,
    fontWeight: "800",
    color: theme.primary,
  },
  summaryBody: {
    marginTop: 14,
  },
  summaryTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: theme.text,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  summaryCouponBlock: {
    marginBottom: 6,
  },
  summaryHint: {
    fontSize: 11,
    fontStyle: "italic",
    paddingLeft: 4,
  },
  summaryLabel: {
    fontSize: 14,
    color: theme.secondaryText,
    fontWeight: "500",
  },
  summaryValue: {
    fontSize: 14,
    fontWeight: "700",
    color: theme.text,
  },
  divider: {
    height: 1,
    backgroundColor: theme.border,
    marginVertical: 12,
  },
  totalLabel: {
    fontSize: 16,
    fontWeight: "800",
    color: theme.text,
  },
  totalValue: {
    fontSize: 19,
    fontWeight: "900",
    color: theme.primary,
  },
  savingsBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: theme.primary + "15",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    marginTop: 12,
    borderWidth: 1,
    borderColor: theme.primary + "30",
  },
  savingsBannerText: {
    fontSize: 12,
    fontWeight: "700",
    color: theme.primary,
    flex: 1,
  },
  // Footer Styles
  footer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: Platform.OS === "ios" ? 32 : 16,
    backgroundColor: theme.background,
    borderTopWidth: 1,
    borderTopColor: theme.border,
    zIndex: 1000,
    ...(Platform.OS === "web" && {
      bottom: 70,
      left: 0,
      right: 0,
      width: "100%",
      maxWidth: 600,
      alignSelf: "center",
      borderTopWidth: 1,
      borderTopColor: theme.border,
      paddingBottom: 12,
    }),
  },
  checkoutButton: {
    height: 54,
    borderRadius: 16,
    paddingHorizontal: 18,
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  checkoutTotalInfo: {
    justifyContent: "center",
  },
  checkoutTotalLabel: {
    color: "rgba(255,255,255,0.8)",
    fontSize: 11,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  checkoutTotalRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 10,
    marginTop: 2,
  },
  checkoutTotalAmount: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "900",
  },
  checkoutSavingsAmount: {
    color: "rgba(255,255,255,0.85)",
    fontSize: 12,
    fontWeight: "700",
    textDecorationLine: "line-through",
  },
  checkoutActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  checkoutText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "800",
  },
  // Empty State Styles
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 32,
    marginTop: 40,
    width: "100%",
    maxWidth: 600,
    alignSelf: "center",
    paddingBottom: Platform.OS === "web" ? 100 : 40,
  },
  emptyTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: theme.text,
    marginTop: 20,
  },
  emptySubtitle: {
    fontSize: 14,
    color: theme.secondaryText,
    textAlign: "center",
    marginTop: 10,
    lineHeight: 22,
    maxWidth: 300,
  },
  shopNowButton: {
    marginTop: 28,
    paddingHorizontal: 28,
    paddingVertical: 14,
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  shopNowText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "800",
  },
  // Coupon Styles
  couponContainer: {
    marginHorizontal: 16,
    marginTop: 20,
    marginBottom: 8,
    borderRadius: 18,
    backgroundColor: theme.tertiaryBackground,
    borderWidth: 1,
    borderColor: theme.border,
    padding: 16,
  },
  couponHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  couponHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  couponTitleIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: theme.primary + "15",
    alignItems: "center",
    justifyContent: "center",
  },
  couponTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: theme.text,
  },
  viewOffersBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: theme.primary,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
  },
  viewOffersText: {
    fontSize: 12,
    fontWeight: "800",
    color: "#fff",
  },
  couponBannerCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: theme.tertiaryBackground,
    borderRadius: 12,
    padding: 12,
    marginTop: 12,
    borderWidth: 1,
    borderColor: theme.border,
  },
  couponBannerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  couponBannerTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: theme.text,
  },
  couponBannerSub: {
    fontSize: 11,
    color: theme.secondaryText,
    marginTop: 2,
  },
  couponBannerAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  couponBannerActionText: {
    fontSize: 12,
    fontWeight: "700",
    color: theme.primary,
  },
  couponInputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.tertiaryBackground,
    borderRadius: 14,
    paddingHorizontal: 12,
    height: 54,
    borderWidth: 1,
    borderColor: theme.border,
  },
  couponInput: {
    flex: 1,
    fontSize: 15,
    color: theme.text,
    fontWeight: "600",
    paddingRight: 8,
  },
  applyButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  applyButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "700",
  },
  couponStatusText: {
    fontSize: 12,
    marginTop: 6,
    marginLeft: 4,
    fontWeight: "600",
  },
  appliedCouponContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: theme.primary + "0F",
    padding: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: theme.primary + "35",
    borderStyle: "dashed",
    gap: 8,
  },
  appliedCouponInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
    minWidth: 0,
  },
  appliedCouponIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: theme.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  couponBadge: {
    backgroundColor: theme.primary,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    alignSelf: "flex-start",
  },
  couponBadgeText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  appliedCouponText: {
    fontSize: 13,
    color: theme.text,
    fontWeight: "700",
  },
  removeCouponText: {
    fontSize: 13,
    color: theme.error || "#ef4444",
    fontWeight: "700",
    paddingVertical: 4,
    paddingHorizontal: 4,
  },
  // Available Coupons List Styles
  availableCouponsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 16,
    marginBottom: 8,
  },
  availableCouponsTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: theme.secondaryText,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  couponCard: {
    backgroundColor: theme.tertiaryBackground,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
    padding: 12,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  couponCardLeft: {
    flex: 1,
    marginRight: 10,
  },
  couponCardCodeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  couponCardCode: {
    fontSize: 13,
    fontWeight: "800",
    color: theme.primary,
    backgroundColor: theme.primary + "15",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: "hidden",
  },
  couponCardDiscount: {
    fontSize: 13,
    fontWeight: "700",
    color: theme.text,
  },
  couponCardDesc: {
    fontSize: 12,
    color: theme.secondaryText,
    lineHeight: 16,
  },
  couponCardMinOrder: {
    fontSize: 11,
    color: theme.tertiaryText,
    marginTop: 2,
  },
  couponApplyBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: theme.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  couponApplyBtnApplied: {
    backgroundColor: theme.border,
  },
  couponApplyBtnText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  couponApplyBtnTextApplied: {
    color: theme.secondaryText,
  },
});
