import { PERMISSIONS } from "./rbac.constants";

export const ROLE_PERMISSION_MAP = {
  USER: [
    PERMISSIONS.VIEW_PRODUCT.code,
    PERMISSIONS.CREATE_ORDER.code,
    PERMISSIONS.CREATE_REVIEW.code,
  ],

  SELLER: [
    PERMISSIONS.CREATE_STORE.code,
    PERMISSIONS.VIEW_STORE.code,
    PERMISSIONS.UPDATE_STORE.code,
    PERMISSIONS.UPDATE_STORE_STATUS.code,

    PERMISSIONS.CREATE_PRODUCT.code,
    PERMISSIONS.CREATE_CLOTHING_PRODUCT.code,
    PERMISSIONS.UPDATE_PRODUCT.code,
    PERMISSIONS.VIEW_ORDER.code,
    PERMISSIONS.UPDATE_ORDER.code,

    PERMISSIONS.CREATE_BANNER.code,
    PERMISSIONS.UPDATE_BANNER.code,
    PERMISSIONS.DELETE_BANNER.code,

    PERMISSIONS.CREATE_COUPON.code,
    PERMISSIONS.UPDATE_COUPON.code,
    PERMISSIONS.DELETE_COUPON.code,
    PERMISSIONS.VIEW_COUPON.code,
    PERMISSIONS.APPLY_COUPON.code,
    PERMISSIONS.VERIFY_COUPON.code,

    PERMISSIONS.CANCEL_ORDER.code,
    PERMISSIONS.RETURN_APPROVE.code,
    PERMISSIONS.RETURN_REJECT.code,

    PERMISSIONS.HANDLE_PAYMENT.code,
    PERMISSIONS.VIEW_PAYOUT.code,
    PERMISSIONS.PROCESS_PAYOUT.code,
    PERMISSIONS.VIEW_TRANSACTIONS.code,

    PERMISSIONS.VIEW_SELLER_ANALYTICS.code,
    PERMISSIONS.VIEW_PLATFORM_ANALYTICS.code,
  ],

  DELIVERY: [
    PERMISSIONS.VIEW_ORDER.code,
    PERMISSIONS.UPDATE_DELIVERY_STATUS.code,
    PERMISSIONS.HANDLE_PAYMENT.code,
    PERMISSIONS.VIEW_PAYOUT.code,
  ],

  ADMIN: [
    PERMISSIONS.CREATE_STORE.code,
    PERMISSIONS.VIEW_STORE.code,
    PERMISSIONS.UPDATE_STORE.code,
    PERMISSIONS.UPDATE_STORE_STATUS.code,
    PERMISSIONS.VERIFY_STORE.code,

    PERMISSIONS.CREATE_CATEGORY.code,
    PERMISSIONS.UPDATE_CATEGORY.code,
    PERMISSIONS.DELETE_CATEGORY.code,
    PERMISSIONS.VIEW_CATEGORY.code,

    PERMISSIONS.CREATE_ATTRIBUTE.code,
    PERMISSIONS.UPDATE_ATTRIBUTE.code,
    PERMISSIONS.DELETE_ATTRIBUTE.code,
    PERMISSIONS.VIEW_ATTRIBUTE.code,

    PERMISSIONS.CREATE_PRODUCT.code,
    PERMISSIONS.CREATE_CLOTHING_PRODUCT.code,
    PERMISSIONS.UPDATE_PRODUCT.code,
    PERMISSIONS.VIEW_ORDER.code,
    PERMISSIONS.UPDATE_ORDER.code,
    PERMISSIONS.UPDATE_STORE_STATUS.code,

    PERMISSIONS.CREATE_BANNER.code,
    PERMISSIONS.UPDATE_BANNER.code,
    PERMISSIONS.DELETE_BANNER.code,

    PERMISSIONS.CREATE_COUPON.code,
    PERMISSIONS.UPDATE_COUPON.code,
    PERMISSIONS.DELETE_COUPON.code,
    PERMISSIONS.VIEW_COUPON.code,
    PERMISSIONS.APPLY_COUPON.code,
    PERMISSIONS.VERIFY_COUPON.code,

    PERMISSIONS.ASSIGN_ROLE.code,
    PERMISSIONS.MANAGE_PERMISSION.code,

    PERMISSIONS.CANCEL_ORDER.code,
    PERMISSIONS.RETURN_APPROVE.code,
    PERMISSIONS.RETURN_REJECT.code,

    PERMISSIONS.HANDLE_PAYMENT.code,
    PERMISSIONS.VIEW_PAYOUT.code,
    PERMISSIONS.PROCESS_PAYOUT.code,
    PERMISSIONS.VIEW_TRANSACTIONS.code,

    PERMISSIONS.VIEW_SELLER_ANALYTICS.code,
    PERMISSIONS.VIEW_PLATFORM_ANALYTICS.code,
  ],

  SUPER_ADMIN: Object.values(PERMISSIONS).map((p) => p.code),
};
