import { StyleSheet, Platform } from "react-native";
import { Theme } from "@/src/theme/Provider/ThemeProvider";

export const createAddressStyles = (theme: Theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background,
    ...(Platform.OS === "web" && {
      alignItems: "center",
    }),
    marginBottom: 30,
  },
  mainWrapper: {
    flex: 1,
    width: "100%",
    maxWidth: 800,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  // Address Card Styles
  addressCard: {
    backgroundColor: theme.tertiaryBackground,
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: theme.border,
    shadowColor: theme.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  activeAddressCard: {
    borderColor: theme.primary,
    borderWidth: 1.5,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  typeBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: theme.background,
  },
  typeText: {
    fontSize: 12,
    fontWeight: "700",
    color: theme.primary,
    textTransform: "uppercase",
  },
  defaultBadge: {
    backgroundColor: "#E3FFEF",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  defaultText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#00C853",
  },
  pinBadge: {
    backgroundColor: "rgba(0, 122, 255, 0.1)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderWidth: 1,
    borderColor: "rgba(0, 122, 255, 0.2)",
  },
  pinText: {
    fontSize: 10,
    fontWeight: "700",
    color: theme.primary,
  },
  nameText: {
    fontSize: 18,
    fontWeight: "700",
    color: theme.text,
    marginBottom: 4,
  },
  phoneText: {
    fontSize: 14,
    color: theme.secondaryText,
    marginBottom: 12,
  },
  addressText: {
    fontSize: 15,
    color: theme.text,
    lineHeight: 22,
    marginBottom: 16,
  },
  cardActions: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderTopColor: theme.border,
    paddingTop: 16,
    gap: 12,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: theme.background,
    borderWidth: 1,
    borderColor: theme.border,
  },
  actionText: {
    fontSize: 13,
    fontWeight: "600",
    color: theme.text,
    marginLeft: 6,
  },
  deleteAction: {
    borderColor: "rgba(255, 59, 48, 0.2)",
  },
  deleteText: {
    color: "#FF3B30",
  },
  // Form Styles
  formContainer: {
    padding: 24,
    marginBottom: 100,
  },
  inputGroup: {
    marginBottom: 20,
  },
  labelRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.secondaryText,
    marginLeft: 8,
  },
  input: {
    height: 56,
    backgroundColor: theme.tertiaryBackground,
    borderRadius: 16,
    paddingHorizontal: 16,
    fontSize: 16,
    color: theme.text,
    borderWidth: 1,
    borderColor: theme.border,
  },
  textArea: {
    height: 100,
    paddingTop: 16,
    textAlignVertical: "top",
  },
  row: {
    flexDirection: "row",
    gap: 16,
  },
  half: {
    flex: 1,
  },
  typeSelector: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 24,
  },
  typeOption: {
    flex: 1,
    height: 50,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: theme.tertiaryBackground,
  },
  selectedTypeOption: {
    borderColor: theme.primary,
    backgroundColor: "rgba(0, 122, 255, 0.05)",
  },
  typeOptionText: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.secondaryText,
  },
  selectedTypeOptionText: {
    color: theme.primary,
  },
  submitButton: {
    backgroundColor: theme.primary,
    height: 58,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    shadowColor: theme.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
    marginBottom: 20
  },
  submitButtonText: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "700",

  },
  errorText: {
    color: theme.error,
    fontSize: 12,
    marginTop: 6,
    marginLeft: 4,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 100,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: theme.text,
    marginTop: 20,
  },
  emptySubtitle: {
    fontSize: 15,
    color: theme.secondaryText,
    textAlign: "center",
    marginTop: 10,
    paddingHorizontal: 40,
  },
  addButtonFloating: {
    position: "absolute",
    bottom: 30,
    right: 30,
    backgroundColor: theme.primary,
    width: 64,
    height: 64,
    borderRadius: 32,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: theme.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 10,
  },
  locationButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0, 122, 255, 0.1)",
    paddingVertical: 12,
    borderRadius: 14,
    marginBottom: 24,
    borderWidth: 1.5,
    borderColor: "rgba(0, 122, 255, 0.3)",
    borderStyle: "dashed",
  },
  locationButtonText: {
    fontSize: 15,
    fontWeight: "700",
    color: theme.primary,
    marginLeft: 10,
  },
  coordinateText: {
    fontSize: 12,
    color: theme.tertiaryText,
    textAlign: "center",
    marginTop: -16,
    marginBottom: 20,
    fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
  },
});
