import { PERMISSIONS, ROLES } from "./rbac.constants";

export const ROLE_PERMISSION_MAP = {
  USER: [
    PERMISSIONS.VIEW_PRODUCT.code,
    PERMISSIONS.CREATE_ORDER.code,
    PERMISSIONS.CREATE_REVIEW.code,
  ],

  SELLER: [
    // Generic permissions
    PERMISSIONS.CREATE_PRODUCT.code,

    // Domain-based product control
    PERMISSIONS.CREATE_CLOTHING_PRODUCT.code,
    PERMISSIONS.CREATE_JEWELRY_PRODUCT.code,
    PERMISSIONS.CREATE_FOOD_PRODUCT.code,

    PERMISSIONS.UPDATE_PRODUCT.code,
    PERMISSIONS.VIEW_ORDER.code,
    PERMISSIONS.UPDATE_ORDER.code,
    PERMISSIONS.UPDATE_STORE_STATUS.code,

    // BANNER CONTROL
    PERMISSIONS.CREATE_BANNER.code,
    PERMISSIONS.UPDATE_BANNER.code,
    PERMISSIONS.DELETE_BANNER.code,

    // COUPON CONTROL
    PERMISSIONS.CREATE_COUPON.code,
    PERMISSIONS.UPDATE_COUPON.code,
    PERMISSIONS.DELETE_COUPON.code,
    PERMISSIONS.VIEW_COUPON.code,
    PERMISSIONS.APPLY_COUPON.code, // user/seller → emit to use coupon
    PERMISSIONS.VERIFY_COUPON.code, // admin to validate coupon

    // ROLE & PERMISSION MANAGEMENT
    PERMISSIONS.ASSIGN_ROLE.code,
    PERMISSIONS.MANAGE_PERMISSION.code,

    // ORDER CONTROL
    PERMISSIONS.CANCEL_ORDER.code,
    PERMISSIONS.RETURN_APPROVE.code,
    PERMISSIONS.RETURN_REJECT.code,

    // PAYMENT CONTROL
    PERMISSIONS.HANDLE_PAYMENT.code,
    PERMISSIONS.VIEW_PAYOUT.code,
    PERMISSIONS.PROCESS_PAYOUT.code,
    PERMISSIONS.VIEW_TRANSACTIONS.code,

    // ANALYTICS
    PERMISSIONS.VIEW_SELLER_ANALYTICS.code,
    PERMISSIONS.VIEW_PLATFORM_ANALYTICS.code,
  ],

  DELIVERY: [
    PERMISSIONS.ASSIGN_DELIVERY.code,
    PERMISSIONS.UPDATE_DELIVERY_STATUS.code,

    // Generic permissions
    PERMISSIONS.CREATE_PRODUCT.code,

    // Domain-based product control
    PERMISSIONS.CREATE_CLOTHING_PRODUCT.code,
    PERMISSIONS.CREATE_JEWELRY_PRODUCT.code,
    PERMISSIONS.CREATE_FOOD_PRODUCT.code,

    PERMISSIONS.UPDATE_PRODUCT.code,
    PERMISSIONS.VIEW_ORDER.code,
    PERMISSIONS.UPDATE_ORDER.code,
    PERMISSIONS.UPDATE_STORE_STATUS.code,

    // BANNER CONTROL
    PERMISSIONS.CREATE_BANNER.code,
    PERMISSIONS.UPDATE_BANNER.code,
    PERMISSIONS.DELETE_BANNER.code,

    // COUPON CONTROL
    PERMISSIONS.CREATE_COUPON.code,
    PERMISSIONS.UPDATE_COUPON.code,
    PERMISSIONS.DELETE_COUPON.code,
    PERMISSIONS.VIEW_COUPON.code,
    PERMISSIONS.APPLY_COUPON.code, // user/seller → emit to use coupon
    PERMISSIONS.VERIFY_COUPON.code, // admin to validate coupon

    // ROLE & PERMISSION MANAGEMENT
    PERMISSIONS.ASSIGN_ROLE.code,
    PERMISSIONS.MANAGE_PERMISSION.code,

    // ORDER CONTROL
    PERMISSIONS.CANCEL_ORDER.code,
    PERMISSIONS.RETURN_APPROVE.code,
    PERMISSIONS.RETURN_REJECT.code,

    // PAYMENT CONTROL
    PERMISSIONS.HANDLE_PAYMENT.code,
    PERMISSIONS.VIEW_PAYOUT.code,
    PERMISSIONS.PROCESS_PAYOUT.code,
    PERMISSIONS.VIEW_TRANSACTIONS.code,

    // ANALYTICS
    PERMISSIONS.VIEW_SELLER_ANALYTICS.code,
    PERMISSIONS.VIEW_PLATFORM_ANALYTICS.code,
  ],

  ADMIN: [
    // Generic permissions
    PERMISSIONS.CREATE_PRODUCT.code,

    // Domain-based product control
    PERMISSIONS.CREATE_CLOTHING_PRODUCT.code,
    PERMISSIONS.CREATE_JEWELRY_PRODUCT.code,
    PERMISSIONS.CREATE_FOOD_PRODUCT.code,

    PERMISSIONS.UPDATE_PRODUCT.code,
    PERMISSIONS.VIEW_ORDER.code,
    PERMISSIONS.UPDATE_ORDER.code,
    PERMISSIONS.UPDATE_STORE_STATUS.code,

    // BANNER CONTROL
    PERMISSIONS.CREATE_BANNER.code,
    PERMISSIONS.UPDATE_BANNER.code,
    PERMISSIONS.DELETE_BANNER.code,

    // COUPON CONTROL
    PERMISSIONS.CREATE_COUPON.code,
    PERMISSIONS.UPDATE_COUPON.code,
    PERMISSIONS.DELETE_COUPON.code,
    PERMISSIONS.VIEW_COUPON.code,
    PERMISSIONS.APPLY_COUPON.code, // user/seller → emit to use coupon
    PERMISSIONS.VERIFY_COUPON.code, // admin to validate coupon

    // ROLE & PERMISSION MANAGEMENT
    PERMISSIONS.ASSIGN_ROLE.code,
    PERMISSIONS.MANAGE_PERMISSION.code,

    // ORDER CONTROL
    PERMISSIONS.CANCEL_ORDER.code,
    PERMISSIONS.RETURN_APPROVE.code,
    PERMISSIONS.RETURN_REJECT.code,

    // PAYMENT CONTROL
    PERMISSIONS.HANDLE_PAYMENT.code,
    PERMISSIONS.VIEW_PAYOUT.code,
    PERMISSIONS.PROCESS_PAYOUT.code,
    PERMISSIONS.VIEW_TRANSACTIONS.code,

    // ANALYTICS
    PERMISSIONS.VIEW_SELLER_ANALYTICS.code,
    PERMISSIONS.VIEW_PLATFORM_ANALYTICS.code,
  ],

  SUPER_ADMIN: Object.values(PERMISSIONS).map((p) => p.code),
};
