import { Platform, StyleSheet } from "react-native";
import type { Theme } from "@/src/theme/Provider/ThemeProvider";

export const createRiderStyles = (theme: Theme) =>
  StyleSheet.create({
    keyboard: { flex: 1, backgroundColor: theme.background },
    content: { padding: 18, paddingBottom: 118 },
    center: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.background,
      gap: 12,
    },
    flexOne: { flex: 1, minWidth: 0 },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
      marginBottom: 14,
    },
    headerText: { flex: 1, minWidth: 0 },
    eyebrow: {
      color: theme.primary,
      fontWeight: "700",
      fontSize: 12,
      textTransform: "uppercase",
    },
    title: { color: theme.text, fontSize: 24, fontWeight: "800", marginTop: 2 },
    muted: { color: theme.secondaryText, fontSize: 13, lineHeight: 18 },
    statusButton: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      backgroundColor: theme.text,
      paddingHorizontal: 12,
      paddingVertical: 9,
      borderRadius: 14,
      minHeight: 42,
    },
    statusOnline: { backgroundColor: theme.primary },
    statusButtonText: { color: theme.background, fontWeight: "800" },
    statusOnlineText: { color: "#fff" },
    tabs: {
      gap: 8,
      paddingRight: 18,
      marginBottom: 10,
    },
    tab: {
      minHeight: 40,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      backgroundColor: theme.secondaryBackground,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 14,
      paddingHorizontal: 12,
      paddingVertical: 9,
    },
    tabSelected: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
    tabText: {
      color: theme.secondaryText,
      fontSize: 12,
      fontWeight: "800",
    },
    tabTextSelected: { color: "#fff" },
    panel: { gap: 14 },
    codCard: {
      backgroundColor: theme.warning + "16",
      borderColor: theme.warning + "55",
      borderWidth: 1,
      padding: 16,
      borderRadius: 16,
    },
    codLabel: { color: theme.warning, fontWeight: "700", fontSize: 12 },
    codAmount: { color: theme.text, fontSize: 24, fontWeight: "900", marginTop: 4 },
    codCopy: { color: theme.secondaryText, fontSize: 12, marginTop: 4, lineHeight: 17 },
    summaryGrid: {
      flexDirection: "row",
      gap: 10,
    },
    summaryTile: {
      flex: 1,
      backgroundColor: theme.secondaryBackground,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 14,
      paddingHorizontal: 10,
      paddingVertical: 12,
      minHeight: 72,
      justifyContent: "center",
    },
    summaryValue: {
      color: theme.text,
      fontSize: 16,
      fontWeight: "900",
    },
    summaryLabel: {
      color: theme.secondaryText,
      fontSize: 11,
      fontWeight: "700",
      marginTop: 4,
    },
    capacityBar: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
      backgroundColor: theme.primary + "12",
      borderWidth: 1,
      borderColor: theme.primary + "35",
      borderRadius: 14,
      padding: 12,
    },
    capacityTitle: {
      color: theme.text,
      fontSize: 13,
      fontWeight: "800",
      marginBottom: 2,
    },
    capacityPill: {
      color: "#fff",
      backgroundColor: theme.primary,
      overflow: "hidden",
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 6,
      fontSize: 12,
      fontWeight: "900",
    },
    sectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
      marginTop: 2,
    },
    sectionTitle: { color: theme.text, fontSize: 17, fontWeight: "800" },
    sectionMeta: {
      color: theme.secondaryText,
      fontSize: 12,
      fontWeight: "800",
    },
    jobTabs: {
      gap: 10,
      paddingRight: 18,
    },
    jobTab: {
      width: 178,
      minHeight: 78,
      justifyContent: "center",
      backgroundColor: theme.secondaryBackground,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 14,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    jobTabSelected: {
      borderColor: theme.primary,
      backgroundColor: theme.primary + "12",
    },
    jobTabId: {
      color: theme.text,
      fontSize: 13,
      fontWeight: "900",
    },
    jobTabIdSelected: { color: theme.primary },
    jobTabStatus: {
      color: theme.secondaryText,
      fontSize: 12,
      fontWeight: "700",
      marginTop: 5,
    },
    jobTabStatusSelected: { color: theme.text },
    emptyCard: {
      alignItems: "center",
      gap: 8,
      backgroundColor: theme.secondaryBackground,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 18,
      borderRadius: 16,
    },
    offerCard: {
      backgroundColor: theme.secondaryBackground,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 14,
      borderRadius: 16,
      ...cardShadow(theme),
    },
    jobCard: {
      backgroundColor: theme.secondaryBackground,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 14,
      borderRadius: 16,
      gap: 12,
      ...cardShadow(theme),
    },
    listCard: {
      backgroundColor: theme.secondaryBackground,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 14,
      borderRadius: 16,
      gap: 9,
      ...cardShadow(theme),
    },
    methodCard: {
      backgroundColor: theme.secondaryBackground,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 14,
      borderRadius: 16,
      gap: 8,
    },
    formCard: {
      backgroundColor: theme.secondaryBackground,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 14,
      borderRadius: 16,
      gap: 10,
    },
    noticeCard: {
      borderWidth: 1,
      padding: 14,
      borderRadius: 16,
      gap: 10,
    },
    noticeWarning: {
      backgroundColor: theme.warning + "12",
      borderColor: theme.warning + "55",
    },
    noticeSuccess: {
      backgroundColor: theme.success + "12",
      borderColor: theme.success + "55",
    },
    noticeTitle: {
      color: theme.text,
      fontSize: 14,
      fontWeight: "900",
      marginBottom: 3,
    },
    noticeCopy: {
      color: theme.secondaryText,
      fontSize: 12,
      lineHeight: 17,
    },
    miniChipRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 7,
    },
    miniChip: {
      color: theme.text,
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 999,
      paddingHorizontal: 9,
      paddingVertical: 5,
      fontSize: 11,
      fontWeight: "800",
      overflow: "hidden",
    },
    warningLine: {
      flexDirection: "row",
      alignItems: "center",
      gap: 7,
      backgroundColor: theme.background,
      borderRadius: 12,
      paddingHorizontal: 10,
      paddingVertical: 9,
    },
    warningLineText: {
      flex: 1,
      color: theme.warning,
      fontSize: 12,
      fontWeight: "800",
      lineHeight: 16,
    },
    rowBetween: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
    offerTop: { flexDirection: "row", justifyContent: "space-between", gap: 10 },
    offerId: { color: theme.text, fontSize: 16, fontWeight: "800", flexShrink: 1 },
    cardTitle: { color: theme.text, fontSize: 15, fontWeight: "800" },
    payout: { color: theme.primary, fontSize: 17, fontWeight: "900" },
    metricsRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 4 },
    metric: {
      color: theme.secondaryText,
      backgroundColor: theme.tertiaryBackground,
      paddingHorizontal: 8,
      paddingVertical: 5,
      borderRadius: 10,
      fontSize: 12,
      overflow: "hidden",
    },
    actionsRow: { flexDirection: "row", gap: 10 },
    primaryButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 7,
      backgroundColor: theme.primary,
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderRadius: 14,
      flex: 1,
      minHeight: 46,
    },
    primaryText: { color: "#fff", fontWeight: "900" },
    secondaryButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 7,
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.border,
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderRadius: 14,
      flex: 1,
      minHeight: 46,
    },
    secondaryText: { color: theme.text, fontWeight: "800" },
    smallPrimaryButton: {
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.primary,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 12,
    },
    smallPrimaryText: { color: "#fff", fontWeight: "900", fontSize: 12 },
    smallSecondaryButton: {
      alignSelf: "flex-start",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.background,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 12,
    },
    cancelButton: {
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: theme.error + "55",
      backgroundColor: theme.error + "10",
      paddingVertical: 12,
      borderRadius: 14,
      minHeight: 46,
    },
    cancelText: { color: theme.error, fontWeight: "800" },
    statusText: { color: theme.primary, fontSize: 13, fontWeight: "800", marginTop: 2 },
    formBlock: { gap: 10 },
    input: {
      backgroundColor: theme.background,
      color: theme.text,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: 12,
      paddingVertical: 11,
      fontSize: 15,
      minHeight: 48,
    },
    multilineInput: {
      minHeight: 88,
      textAlignVertical: "top",
    },
    inlineInputs: {
      flexDirection: "row",
      gap: 10,
    },
    dateInput: {
      flex: 1,
    },
    dateFieldWrap: {
      flex: 1,
      minWidth: 0,
    },
    dateField: {
      minHeight: 52,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      backgroundColor: theme.background,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: 12,
      paddingVertical: 9,
    },
    dateFieldLabel: {
      color: theme.secondaryText,
      fontSize: 11,
      fontWeight: "800",
      marginBottom: 2,
    },
    dateFieldValue: {
      color: theme.text,
      fontSize: 14,
      fontWeight: "800",
    },
    proofGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      marginTop: 2,
    },
    proofItem: {
      width: 126,
      gap: 6,
    },
    proofImage: {
      width: "100%",
      aspectRatio: 1,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.tertiaryBackground,
    },
    proofLabel: {
      color: theme.secondaryText,
      fontSize: 11,
      fontWeight: "800",
    },
    filterChips: {
      gap: 8,
      paddingRight: 18,
    },
    filterChip: {
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.secondaryBackground,
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 8,
      minHeight: 36,
      justifyContent: "center",
    },
    filterChipSelected: {
      borderColor: theme.primary,
      backgroundColor: theme.primary,
    },
    filterChipDisabled: {
      opacity: 0.62,
    },
    filterChipText: {
      color: theme.secondaryText,
      fontWeight: "800",
      fontSize: 12,
    },
    filterChipMeta: {
      color: theme.tertiaryText,
      fontSize: 9,
      fontWeight: "900",
      marginTop: 2,
    },
    filterChipTextSelected: { color: "#fff" },
    statusPill: {
      maxWidth: 142,
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 9,
      paddingVertical: 5,
    },
    statusPillText: {
      fontSize: 10,
      fontWeight: "900",
    },
    greenPill: { borderColor: theme.success + "66", backgroundColor: theme.success + "12" },
    greenPillText: { color: theme.success },
    redPill: { borderColor: theme.error + "66", backgroundColor: theme.error + "12" },
    redPillText: { color: theme.error },
    amberPill: { borderColor: theme.warning + "66", backgroundColor: theme.warning + "12" },
    amberPillText: { color: theme.warning },
    bluePill: { borderColor: theme.primary + "66", backgroundColor: theme.primary + "12" },
    bluePillText: { color: theme.primary },
    mutedTonePill: { borderColor: theme.border, backgroundColor: theme.tertiaryBackground },
    mutedTonePillText: { color: theme.secondaryText },
    segmentSelected: {
      borderColor: theme.primary,
      backgroundColor: theme.primary,
    },
    segmentSelectedText: {
      color: "#fff",
    },
    loadMoreButton: {
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: theme.secondaryBackground,
      borderWidth: 1,
      borderColor: theme.border,
      paddingVertical: 12,
      borderRadius: 14,
      minHeight: 46,
    },
    primaryLine: { color: theme.primary, fontSize: 12, fontWeight: "800" },
    errorText: { color: theme.error, fontSize: 12, fontWeight: "700" },
    busyOverlay: {
      position: "absolute",
      right: 18,
      bottom: 112,
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: theme.primary,
      alignItems: "center",
      justifyContent: "center",
      ...cardShadow(theme),
    },
  });

const cardShadow = (theme: Theme) =>
  Platform.select({
    ios: {
      shadowColor: theme.shadow,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 10,
    },
    android: {
      elevation: 2,
    },
    default: {},
  });
