import { StyleSheet, Dimensions } from "react-native";
import { Theme } from "@/src/theme/colors";

const { width } = Dimensions.get("window");
const COLUMN_WIDTH = (width - 48) / 2;

export const createWishlistStyles = (theme: Theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    // Top app bar (same language as Notifications)
    appBar: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 12,
      paddingTop: 8,
      paddingBottom: 12,
      gap: 8,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.secondaryBackground,
      alignItems: "center",
      justifyContent: "center",
    },
    appBarTitleWrap: {
      flex: 1,
      paddingHorizontal: 4,
    },
    appBarTitle: {
      fontSize: 22,
      fontWeight: "800",
      color: theme.text,
      letterSpacing: -0.4,
    },
    appBarSubtitle: {
      fontSize: 12,
      color: theme.secondaryText,
      fontWeight: "500",
      marginTop: 2,
    },
    list: {
      paddingHorizontal: 16,
      paddingTop: 16,
    },
    grid: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
    },
    card: {
      width: COLUMN_WIDTH,
      marginBottom: 20,
      borderRadius: 12,
      backgroundColor: theme.background,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: theme.border,
    },
    imageContainer: {
      width: "100%",
      height: COLUMN_WIDTH * 1.3,
      position: "relative",
      backgroundColor: theme.secondaryBackground,
    },
    image: {
      width: "100%",
      height: "100%",
      backgroundColor: theme.secondaryBackground,
    },
    discountBadge: {
      position: "absolute",
      top: 8,
      left: 8,
      backgroundColor: theme.primary,
      paddingHorizontal: 6,
      paddingVertical: 3,
      borderRadius: 4,
      zIndex: 10,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.15,
      shadowRadius: 2,
      elevation: 2,
    },
    discountText: {
      color: "#fff",
      fontSize: 10,
      fontWeight: "800",
      letterSpacing: 0.2,
    },
    removeBtn: {
      position: "absolute",
      top: 8,
      right: 8,
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: "rgba(255, 255, 255, 0.9)",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 10,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    info: {
      padding: 10,
    },
    brand: {
      fontSize: 11,
      fontWeight: "800",
      color: theme.text,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      marginBottom: 2,
    },
    title: {
      fontSize: 12,
      color: theme.secondaryText,
      marginBottom: 6,
    },
    priceRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    price: {
      fontSize: 14,
      fontWeight: "800",
      color: theme.text,
    },
    originalPrice: {
      fontSize: 11,
      color: theme.secondaryText,
      textDecorationLine: "line-through",
    },
    discount: {
      fontSize: 11,
      fontWeight: "700",
      color: theme.primary,
    },
    emptyContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 32,
      paddingBottom: 40,
    },
    emptyIconWrap: {
      width: 110,
      height: 110,
      borderRadius: 55,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 18,
    },
    emptyTitle: {
      fontSize: 20,
      fontWeight: "800",
      color: theme.text,
      textAlign: "center",
      letterSpacing: -0.3,
    },
    emptySubtitle: {
      fontSize: 14,
      color: theme.secondaryText,
      textAlign: "center",
      lineHeight: 20,
      marginTop: 8,
      maxWidth: 320,
    },
    shopBtn: {
      marginTop: 20,
      paddingHorizontal: 24,
      height: 48,
      borderRadius: 24,
      backgroundColor: theme.primary,
      justifyContent: "center",
      alignItems: "center",
    },
    shopBtnText: {
      color: "#fff",
      fontSize: 14,
      fontWeight: "800",
      letterSpacing: 0.3,
    },
  });
