import { StyleSheet, Dimensions, Platform } from "react-native";

const { width: SCREEN_WIDTH } = Dimensions.get("window");

export { SCREEN_WIDTH };

export const styles = StyleSheet.create({
  root: { flex: 1 },
  scrollView: { flex: 1 },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
  },
  loadingText: { fontSize: 14, fontWeight: "500" },

  // Gallery
  galleryContainer: { position: "relative" },
  galleryImage: { width: "100%", height: "100%" },
  galleryNav: {
    position: "absolute",
    top: Platform.OS === "ios" ? 52 : 36,
    left: 16,
    right: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    zIndex: 10,
  },
  navRight: { flexDirection: "row" },
  navBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  counterPill: {
    position: "absolute",
    bottom: 60,
    right: 16,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.55)",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
  },
  counterText: { color: "#fff", fontSize: 11, fontWeight: "700" },
  thumbStrip: { position: "absolute", bottom: 10, left: 0, right: 0 },
  thumbStripContent: { paddingHorizontal: 16, gap: 8 },
  thumbImage: { width: 40, height: 40, borderRadius: 6 },

  // Info Section
  infoSection: { paddingHorizontal: 16, paddingTop: 16, paddingBottom: 12 },
  brandName: {
    fontSize: 15,
    fontWeight: "800",
    letterSpacing: 0.3,
    marginBottom: 4,
  },
  productTitle: {
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 20,
    marginBottom: 10,
  },
  ratingChip: { flexDirection: "row", alignItems: "center", marginBottom: 14 },
  ratingChipInner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#34C759",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    gap: 3,
  },
  ratingChipScore: { color: "#fff", fontSize: 12, fontWeight: "800" },
  ratingDividerLine: { width: 1, height: 14, backgroundColor: "#D1D5DB", marginHorizontal: 8 },
  ratingChipCount: { fontSize: 13, fontWeight: "500" },
  priceBlock: { flexDirection: "row", alignItems: "baseline", gap: 8 },
  currentPrice: { fontSize: 22, fontWeight: "800" },
  mrp: { fontSize: 13, fontWeight: "500" },
  mrpStrike: { textDecorationLine: "line-through" },
  discountChip: {
    backgroundColor: "#FF6B35",
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 4,
  },
  discountChipText: { color: "#fff", fontSize: 11, fontWeight: "800" },
  taxInfo: { fontSize: 12, fontWeight: "500", marginTop: 4 },

  // Section Divider
  sectionDivider: { height: 8, width: "100%" },

  // Selection sections
  selectionSection: { paddingHorizontal: 16, paddingVertical: 16 },
  selectionLabel: {
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.8,
    marginBottom: 14,
  },
  colorRow: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  colorOption: {
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 20,
    borderWidth: 1.5,
  },
  colorOptionText: { fontSize: 13, fontWeight: "600" },
  sizeHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  sizeGuideBtn: { flexDirection: "row", alignItems: "center", gap: 4 },
  sizeGuideText: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  sizeRow: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  sizeCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1.5,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    overflow: "hidden",
  },
  sizeCircleOOS: { borderStyle: "dashed" },
  sizeText: { fontSize: 14, fontWeight: "600" },
  sizeTextOOS: { textDecorationLine: "line-through" },
  oosLine: {
    position: "absolute",
    width: "140%",
    height: 1,
    transform: [{ rotate: "-45deg" }],
  },
  lowStockRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 12,
  },
  lowStockText: { fontSize: 12, fontWeight: "600" },

  // Delivery
  deliverySection: { paddingHorizontal: 16, paddingVertical: 16 },
  deliveryCards: { gap: 10, marginBottom: 20 },
  deliveryCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    gap: 12,
  },
  deliveryCardText: { flex: 1 },
  deliveryCardTitle: { fontSize: 13, fontWeight: "700", marginBottom: 2 },
  deliveryCardSub: { fontSize: 12 },
  policiesRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingTop: 8,
  },
  policyItem: { alignItems: "center", gap: 6, flex: 1 },
  policyIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    justifyContent: "center",
    alignItems: "center",
  },
  policyLabel: {
    fontSize: 10,
    fontWeight: "600",
    textAlign: "center",
    lineHeight: 14,
  },

  // Expandable
  expandableSectionWrap: { paddingHorizontal: 16 },
  expandableContainer: { borderBottomWidth: 1 },
  expandableHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 16,
  },
  expandableTitle: { fontSize: 14, fontWeight: "700", letterSpacing: 0.3 },
  expandableBody: { paddingBottom: 16 },
  descriptionText: { fontSize: 13, lineHeight: 20, marginBottom: 16 },
  specsTable: { marginTop: 4 },
  specTableRow: {
    flexDirection: "row",
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  specKey: { flex: 0.4, fontSize: 13, fontWeight: "500" },
  specVal: { flex: 0.6, fontSize: 13, fontWeight: "600" },
  returnPolicyContent: { gap: 10 },
  returnRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  returnText: { fontSize: 13, flex: 1 },

  // Ratings & Reviews
  reviewsSection: { paddingHorizontal: 16, paddingVertical: 16 },
  ratingOverview: { flexDirection: "row", marginBottom: 24 },
  ratingLeft: { alignItems: "center", paddingRight: 20, borderRightWidth: StyleSheet.hairlineWidth, borderRightColor: "#E5E7EB" },
  bigRating: { fontSize: 38, fontWeight: "800", lineHeight: 44 },
  starsRow: { flexDirection: "row", gap: 2, marginTop: 4, marginBottom: 4 },
  totalRatings: { fontSize: 11, fontWeight: "500" },
  ratingRight: { flex: 1, paddingLeft: 16, justifyContent: "center", gap: 4 },
  ratingBarRow: { flexDirection: "row", alignItems: "center", gap: 4 },
  ratingBarLabel: { width: 12, fontSize: 11, fontWeight: "600", textAlign: "right" },
  ratingBarTrack: { flex: 1, height: 5, borderRadius: 3, overflow: "hidden" },
  ratingBarFill: { height: "100%", borderRadius: 3 },
  ratingBarCount: { width: 28, fontSize: 10, textAlign: "right" },

  reviewsList: {},
  reviewCard: { paddingVertical: 16, borderBottomWidth: StyleSheet.hairlineWidth },
  reviewTopRow: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 8 },
  miniRatingPill: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    gap: 3,
  },
  miniRatingText: { color: "#fff", fontSize: 11, fontWeight: "800" },
  reviewTitle: { fontSize: 14, fontWeight: "600", flex: 1 },
  reviewBody: { fontSize: 13, lineHeight: 19, marginBottom: 8 },
  reviewImagesRow: { marginBottom: 10 },
  reviewThumb: {
    width: 64,
    height: 64,
    borderRadius: 8,
    borderWidth: 1,
    marginRight: 8,
  },
  reviewerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  reviewerImg: { width: 20, height: 20, borderRadius: 10 },
  reviewerName: { fontSize: 12, fontWeight: "500" },
  reviewDot: { fontSize: 8 },
  reviewerDate: { fontSize: 11 },
  helpfulBtn: { flexDirection: "row", alignItems: "center", gap: 4 },
  helpfulText: { fontSize: 12, fontWeight: "500" },
  viewAllBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    borderWidth: 1,
    borderRadius: 8,
    marginTop: 16,
    gap: 4,
  },
  viewAllText: { fontSize: 13, fontWeight: "700", letterSpacing: 0.3 },

  // Bottom Bar
  bottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: Platform.OS === "ios" ? 32 : 14,
    borderTopWidth: 1,
    gap: 12,
  },
  wishlistBtn: {
    flex: 1,
    height: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderRadius: 6,
    gap: 8,
  },
  wishlistBtnText: { fontSize: 13, fontWeight: "700", letterSpacing: 0.5 },
  addToBagBtn: {
    flex: 1.5,
    height: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 6,
    gap: 8,
  },
  addToBagText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0.5,
  },

  // Similar Products
  similarSection: { paddingVertical: 16 },
  similarScroll: { paddingHorizontal: 16, gap: 12 },
  similarCard: {
    width: 150,
    borderRadius: 10,
    borderWidth: 1,
    overflow: "hidden",
  },
  similarImage: { width: "100%", height: 180 },
  similarInfo: { padding: 10, gap: 3 },
  similarBrand: { fontSize: 11, fontWeight: "700", textTransform: "uppercase", letterSpacing: 0.3 },
  similarTitle: { fontSize: 12, fontWeight: "400", lineHeight: 16 },
  similarPriceRow: { flexDirection: "row", alignItems: "baseline", gap: 4, marginTop: 4 },
  similarPrice: { fontSize: 13, fontWeight: "800" },
  similarMrp: { fontSize: 11, textDecorationLine: "line-through" },
  similarRating: { flexDirection: "row", alignItems: "center", gap: 4, marginTop: 4 },
  similarRatingPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#34C759",
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 3,
    gap: 2,
  },
  similarRatingText: { color: "#fff", fontSize: 10, fontWeight: "800" },
  similarRatingCount: { fontSize: 10 },
});
